-- Demo data is now loaded by `pnpm data:import` (Data stream D4).
-- It imports the real ROPS Innovation Library plus fictional pilots, reviews
-- and submissions that contain no personal data.
-- Do not add raw insert statements here: reset the local database and run
-- `pnpm exec supabase db reset --include-seed && pnpm data:import` instead.
